### ISSUE TITLE
gemfile.lock makes it hard to test changes

### ISSUE THREAD

**Issue by ianrrees** [codecraft-dunedin/codecraft-dunedin.github.io#4]
At least on my system, it specifies newer versions of some packages than I have installed, so `jekyll serve` doesn't go.  I'm not too familiar with Ruby, what's the best way to get things working locally?

**Comment by ianrrees** [comment]
Ah, I've had the good fortune of meeting a more experienced Ruby person this evening.  At first, using `bundle exec jekyll serve' gives ~100 level traceback where this seems to be the culprit:  

```
Liquid Exception: uninitialized constant Kramdown::Utils::OrderedHash in /_layouts/default.html
jekyll 3.8.6 | Error:  uninitialized constant Kramdown::Utils::OrderedHash
```

We then realised that the apt installed jekyll was conflicting; removing that and `bundle install`ing with a few sudo's seemed to work!

**Comment by veb** [comment]
I apologise, I will be making a better README shortly.
